generatorName: java
outputDir: samples/config/petstore/java
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/java
additionalProperties:
  hideGenerationTimestamp: "true"
